process.env.MODE = 'custom';
process.env.WRITE_SNAPSHOTS = 'false';
process.env.ENABLE_BOOK_TICKER = 'true';
process.env.ENABLE_DEPTH = 'false';
process.env.ENABLE_AGG_TRADES = 'false';
process.env.ENABLE_FORCE_ORDERS = 'false';
process.env.ENABLE_MARK_PRICE = 'false';
process.env.ENABLE_TICKER_STREAM = 'false';
process.env.ENABLE_KLINE_1M = 'false';
process.env.ENABLE_KLINE_5M = 'false';
require('./collector');
